package nus.iss.team2.ADProjectTECHS;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

import nus.iss.team2.ADProjectTECHS.Model.Enums.Gender;
import nus.iss.team2.ADProjectTECHS.Service.MemberService;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

import nus.iss.team2.ADProjectTECHS.Controller.DeveloperController.DeveloperController;
import nus.iss.team2.ADProjectTECHS.Model.CourseCrawled;
import nus.iss.team2.ADProjectTECHS.Model.Enums.Education;
import nus.iss.team2.ADProjectTECHS.Model.Job;
import nus.iss.team2.ADProjectTECHS.Model.JobSkill;
import nus.iss.team2.ADProjectTECHS.Model.Member;
import nus.iss.team2.ADProjectTECHS.Model.MyCourse;
import nus.iss.team2.ADProjectTECHS.Model.MySkill;
import nus.iss.team2.ADProjectTECHS.Model.ScheduleEvent;
import nus.iss.team2.ADProjectTECHS.Model.Skill;
import nus.iss.team2.ADProjectTECHS.Repository.CourseCrawledRepository;
import nus.iss.team2.ADProjectTECHS.Repository.JobRepository;
import nus.iss.team2.ADProjectTECHS.Repository.JobSkillRepository;
import nus.iss.team2.ADProjectTECHS.Repository.MemberRepository;
import nus.iss.team2.ADProjectTECHS.Repository.MyCourseRepository;
import nus.iss.team2.ADProjectTECHS.Repository.MySkillRepository;
import nus.iss.team2.ADProjectTECHS.Repository.ScheduleEventRepository;
import nus.iss.team2.ADProjectTECHS.Repository.SkillRepository;
import org.springframework.security.config.annotation.method.configuration.EnableGlobalMethodSecurity;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.security.crypto.password.PasswordEncoder;

@SpringBootApplication
@EnableGlobalMethodSecurity(prePostEnabled = true, securedEnabled = true)
public class AdProjectTechsApplication {

	public static void main(String[] args) {
		SpringApplication.run(AdProjectTechsApplication.class, args);
	}

	@Bean
	public PasswordEncoder passwordEncoder() {
		return new BCryptPasswordEncoder();
		
	}
    @Bean
	CommandLineRunner loadData(CourseCrawledRepository ccRepo,
							   MemberService mRepo,
							   ScheduleEventRepository seRepo,
							   JobSkillRepository jsRepo,
							   JobRepository jRepo,
							   MySkillRepository msRepo,
							   MyCourseRepository mcRepo,
							   SkillRepository sRepo) {
		return (args) -> {
			CourseCrawled cc1 = new CourseCrawled();
			cc1.setCourseTitle("Telugu");
			cc1.setUrlLink("https://google.cn/vivamus/vestibulum/sagittis/sapien/cum.js");
			cc1.setViews(100000);
			cc1.setLikes(132432);
			cc1.setSubscribers(1758892);
			cc1.setDate(LocalDate.parse("2022-09-01"));
			cc1.setDuration("PT12H37M23S");
			CourseCrawled cc2 = new CourseCrawled();
			cc2.setCourseTitle("French");
			cc2.setUrlLink("http://mac.com/imperdiet/sapien/urna.xml");
			cc2.setViews(290779);
			cc2.setLikes(23355);
			cc2.setSubscribers(233335);
			cc2.setDate(LocalDate.parse("2022-09-03"));
			cc2.setDuration("PT34M45S");
			CourseCrawled cc3 = new CourseCrawled();
			cc3.setCourseTitle("Tetum");
			cc3.setUrlLink("https://smh.com.au/laoreet/ut/rhoncus/aliquet/pulvinar/sed/nisl.jpg");
			cc3.setViews(3743232);
			cc3.setLikes(366432);
			cc3.setSubscribers(335545);
			cc3.setDate(LocalDate.parse("2022-09-04"));
			cc3.setDuration("P1DT17H1M37S");
			CourseCrawled cc4 = new CourseCrawled();
			cc4.setCourseTitle("Kyrgyz");
			cc4.setUrlLink("https://symantec.com/nisl/nunc.json");
			cc4.setViews(4523266);
			cc4.setLikes(496464);
			cc4.setSubscribers(455479);
			cc4.setDate(LocalDate.parse("2022-09-05"));
			cc4.setDuration("PT11H56M54S");
			CourseCrawled cc5 = new CourseCrawled();
			cc5.setCourseTitle("Swati");
			cc5.setUrlLink("http://boston.com/leo/odio/condimentum/id/luctus.js");
			cc5.setViews(5643234);
			cc5.setLikes(597766);
			cc5.setSubscribers(546797);
			cc5.setDate(LocalDate.parse("2022-09-07"));
			cc5.setDuration("PT21M31S");
			CourseCrawled cc6 = new CourseCrawled();
			cc6.setCourseTitle("Lao");
			cc6.setUrlLink("https://nps.gov/est/quam/pharetra/magna/ac.xml");
			cc6.setViews(646346);
			cc6.setLikes(6098762);
			cc6.setSubscribers(6876453);
			cc6.setDate(LocalDate.parse("2022-09-08"));
			cc6.setDuration("PT1H21M31S");
			CourseCrawled cc7 = new CourseCrawled();
			cc7.setCourseTitle("Irish Gaelic");
			cc7.setUrlLink("https://phoca.cz/congue/vivamus/metus/arcu/adipiscing/molestie/hendrerit.html");
			cc7.setViews(7754452);
			cc7.setLikes(76342);
			cc7.setSubscribers(7786753);
			cc7.setDate(LocalDate.parse("2022-09-09"));
			cc7.setDuration("PT2H21M31S");
			CourseCrawled cc8 = new CourseCrawled();
			cc8.setCourseTitle("Estonian");
			cc8.setUrlLink("https://squidoo.com/cras/non/velit.js");
			cc8.setViews(885643);
			cc8.setLikes(8562547);
			cc8.setDate(LocalDate.parse("2022-09-10"));
			cc8.setDuration("PT3H21M31S");
			CourseCrawled cc9 = new CourseCrawled();
			cc9.setCourseTitle("Nepali");
			cc9.setUrlLink("https://bbc.co.uk/mi/pede/malesuada.js");
			cc9.setViews(986654);
			cc9.setLikes(954322);
			cc9.setSubscribers(965422);
			cc9.setDate(LocalDate.parse("2022-09-11"));
			cc9.setDuration("PT4H21M31S");
			CourseCrawled cc10 = new CourseCrawled();
			cc10.setCourseTitle("Aymara");
			cc10.setUrlLink("https://berkeley.edu/iaculis.aspx");
			cc10.setViews(104775);
			cc10.setSubscribers(105341);
			cc10.setLikes(1085633);
			cc10.setDate(LocalDate.parse("2022-09-13"));
			cc10.setDuration("PT4H21M31S");
			CourseCrawled cc11 = new CourseCrawled();
			cc11.setCourseTitle("Dari");
			cc11.setUrlLink("https://woothemes.com/magna/vestibulum/aliquet/ultrices.json");
			cc11.setViews(1186544);
			cc11.setLikes(11437769);
			cc11.setSubscribers(1187423);
			cc11.setDate(LocalDate.parse("2022-08-01"));
			cc11.setDuration("PT5H21M31S");
			CourseCrawled cc12 = new CourseCrawled();
			cc12.setCourseTitle("Hindi");
			cc12.setUrlLink("https://www.youtube.com/watch?v=HXV3zeQKqGY");
			cc12.setViews(12967554);
			cc12.setLikes(12867667);
			cc12.setSubscribers(12076733);
			cc12.setDate(LocalDate.parse("2022-08-10"));
			cc12.setDuration("PT7H21M31S");
			CourseCrawled cc13 = new CourseCrawled();
			cc13.setCourseTitle("Latvian");
			cc13.setUrlLink("https://cyberchimps.com/vel/lectus/in.aspx");
			cc13.setViews(138764);
			cc13.setLikes(1387644);
			cc13.setSubscribers(13896732);
			cc13.setDate(LocalDate.parse("2022-07-10"));
			cc13.setDuration("PT21M31S");
			CourseCrawled cc14 = new CourseCrawled();
			cc14.setCourseTitle("Swahili");
			cc14.setUrlLink("https://spotify.com/eleifend/quam/a.jsp");
			cc14.setViews(14873456);
			cc14.setLikes(1466365);
			cc14.setSubscribers(1486466);
			cc14.setDate(LocalDate.parse("2022-07-30"));
			cc14.setDuration("PT1H21M31S");
			CourseCrawled cc15 = new CourseCrawled();
			cc15.setCourseTitle("Moldovan");
			cc15.setUrlLink("https://independent.co.uk/tortor/quis/turpis.jsp");
			cc15.setViews(1587652);
			cc15.setLikes(1508988);
			cc15.setSubscribers(1598773);
			cc14.setDate(LocalDate.parse("2022-05-30"));
			cc14.setDuration("PT1H21M31S");
			CourseCrawled cc16 = new CourseCrawled();
			cc16.setCourseTitle("Pashto");
			cc16.setUrlLink("https://www.youtube.com/watch?v=mAtkPQO1FcA&t=44s");
			cc16.setViews(168674);
			cc16.setLikes(1646899);
			cc16.setSubscribers(1676433);
			cc16.setDate(LocalDate.parse("2022-04-30"));
			cc16.setDuration("PT1H21M31S");
			CourseCrawled cc17 = new CourseCrawled();
			cc17.setCourseTitle("Romanian");
			cc17.setUrlLink("http://thetimes.co.uk/orci/luctus.html");
			cc17.setViews(1797656);
			cc17.setLikes(1775632);
			cc17.setSubscribers(1737657);
			cc17.setDate(LocalDate.parse("2022-04-06"));
			cc17.setDuration("PT2H21M31S");
			CourseCrawled cc18 = new CourseCrawled();
			cc18.setCourseTitle("Oriya");
			cc18.setUrlLink("https://tinypic.com/ut/mauris.aspx");
			cc18.setViews(1896742);
			cc18.setLikes(1885534);
			cc18.setSubscribers(1886753);
			cc18.setDate(LocalDate.parse("2022-04-22"));
			cc18.setDuration("PT3H21M31S");
			CourseCrawled cc19 = new CourseCrawled();
			cc19.setCourseTitle("Spanish");
			cc19.setUrlLink("http://nsw.gov.au/nisi/venenatis/tristique/fusce/congue.jpg");
			cc19.setViews(198563);
			cc19.setLikes(198797);
			cc19.setSubscribers(1973452);
			cc19.setDate(LocalDate.parse("2022-05-11"));
			cc19.setDuration("PT1H21M31S");
			CourseCrawled cc20 = new CourseCrawled();
			cc20.setCourseTitle("Luxembourgish");
			cc20.setUrlLink("http://berkeley.edu/curae/donec/pharetra.asp");
			cc20.setViews(2034532);
			cc20.setLikes(2097868);
			cc20.setSubscribers(2012345);
			cc20.setDate(LocalDate.parse("2022-11-30"));
			cc20.setDuration("PT4H21M31S");

			Skill s1 = new Skill();
			s1.setUrlLink("http://hexun.com/rhoncus/aliquet/pulvinar/sed/nisl/nunc/rhoncus.html");
			s1.setSkillTitle("C sharp");
			cc1.setSkill(s1);
			s1.setSkillDescription("HTML (HyperText Markup Language) is a standard markup language for web page creation. It allows the creation and structure of sections, paragraphs, and links using HTML elements (the building blocks of a web page) such as tags and attributes.");
			Skill s2 = new Skill();
			s2.setUrlLink("https://www.youtube.com/watch?v=mAtkPQO1FcA");
			s2.setSkillTitle("Java");
			cc2.setSkill(s2);
			s2.setSkillDescription("JavaScript is a scripting language that enables you to create dynamically updating content, control multimedia, animate images, and pretty much everything else.");
			Skill s3 = new Skill();
			s3.setUrlLink("http://usa.gov/vitae.jsp");
			s3.setSkillTitle("Java Web");
			cc3.setSkill(s3);
			s3.setSkillDescription("SQL (Structured Query Language) is a popular query language designed for managing data held in databases. It is frequently used in all types of applications as it integrates well with different programming languages.");
			Skill s4 = new Skill();
			s4.setUrlLink("http://vinaora.com/consequat.aspx");
			s4.setSkillTitle("Spring 5 Framwork");
			cc4.setSkill(s4);
			Skill s5 = new Skill();
			s5.setUrlLink("https://usa.gov/eros/suspendisse/accumsan.jpg");
			s5.setSkillTitle("Spring MVC");
			cc5.setSkill(s5);
			Skill s6 = new Skill();
			s6.setUrlLink("http://nifty.com/ac/tellus/semper/interdum/mauris/ullamcorper.js");
			s6.setSkillTitle("Python");
			cc6.setSkill(s6);
			Skill s7 = new Skill();
			s7.setUrlLink("https://usnews.com/nunc/nisl/duis/bibendum/felis/sed/interdum.html");
			s7.setSkillTitle("Web Crawling");
			cc7.setSkill(s7);
			Skill s8 = new Skill();
			s8.setUrlLink("http://sciencedirect.com/lacus/curabitur/at.jpg");
			s8.setSkillTitle("HTML");
			cc8.setSkill(s8);
			s8.setSkillDescription("SQL (Structured Query Language) is a popular query language designed for managing data held in databases. It is frequently used in all types of applications as it integrates well with different programming languages.");
			Skill s9 = new Skill();
			s9.setUrlLink("http://phoca.cz/quam.png");
			s9.setSkillTitle("CSS");
			cc9.setSkill(s9);
			Skill s10 = new Skill();
			s10.setUrlLink("https://bluehost.com/purus/sit/amet/nulla/quisque.jpg");
			s10.setSkillTitle("Spring Boot");
			cc10.setSkill(s10);
			Skill s11 = new Skill();
			s11.setUrlLink("http://is.gd/aliquam.json");
			s11.setSkillTitle("Javascript");
			cc11.setSkill(s11);
			Skill s12 = new Skill();
			s12.setUrlLink("https://naver.com/et/magnis/dis.png");
			s12.setSkillTitle("Relational Database");
			cc12.setSkill(s12);
			Skill s13 = new Skill();
			s13.setUrlLink("http://wsj.com/quisque/arcu/libero/rutrum.jsp");
			s13.setSkillTitle("Back End");
			cc13.setSkill(s13);
			Skill s14 = new Skill();
			s14.setUrlLink("http://admin.ch/tellus/semper/interdum.aspx");
			s14.setSkillTitle("Quality Assurance");
			cc14.setSkill(s14);
			Skill s15 = new Skill();
			s15.setUrlLink("https://shop-pro.jp/sociis/natoque.json");
			s15.setSkillTitle("Data Analysis");
			cc15.setSkill(s15);
			Skill s16 = new Skill();
			s16.setUrlLink("https://www.youtube.com/watch?v=WG5ikvJ2TKA");
			s16.setSkillTitle("Frond End");
			cc16.setSkill(s16);
			Skill s17 = new Skill();
			s17.setUrlLink("http://blogspot.com/nonummy/maecenas/tincidunt/lacus.jpg");
			s17.setSkillTitle("Data Virtualization");
			cc17.setSkill(s17);
			Skill s18 = new Skill();
			s18.setUrlLink("https://networkadvertising.org/quis/orci.xml");
			s18.setSkillTitle("Machine Learning");
			cc18.setSkill(s18);
			Skill s19 = new Skill();
			s19.setUrlLink("https://nbcnews.com/sed.jpg");
			s19.setSkillTitle("Responsive Web Design");
			cc19.setSkill(s19);
			Skill s20 = new Skill();
			s20.setUrlLink("http://telegraph.co.uk/sed/lacus/morbi/sem/mauris.json");
			s20.setSkillTitle("Ruby");
			cc20.setSkill(s20);

			Member m1 = new Member();
			m1.setUsername("test");
			m1.setPassword("test");
			m1.setEmail("tscandred0@gov.uk");
			m1.setGender(Gender.MALE);
			m1.setBirthday(LocalDate.of(1983, 5, 22));
			m1.setCourseTaken("Java");
			m1.setCurrentCity("Usukhchay");
			m1.setEducation(Education.OTHERS);
			m1.setShortBio("matrix frictionless systems");
			m1.setCurrentJobTitle("Tax Accountant");
			m1.setAvatar("https://robohash.org/reiciendisrerumin.png?size=50x50&set=set1");
			Member m2 = new Member();
			m2.setUsername("abc");
			m2.setPassword("abc");
			m2.setEmail("jthresh1@census.gov");
			m2.setGender(Gender.MALE);
			m2.setCourseTaken("Spring Boot");
			m2.setBirthday(LocalDate.of(1987, 11, 20));
			m2.setCurrentCity("La Gi");
			m2.setEducation(Education.MASTER);
			m2.setShortBio("integrate web-enabled e-business");
			m2.setCurrentJobTitle("Actuary");
			m2.setAvatar("https://robohash.org/laboriosamperspiciatisvitae.png?size=50x50&set=set1");
			Member m3 = new Member();
			m3.setUsername("kjillins2");
			m3.setPassword("7UoGHc");
			m3.setEmail("sfarrar2@alibaba.com");
			m3.setGender(Gender.MALE);
			m3.setCourseTaken("C sharp");
			m3.setBirthday(LocalDate.of(1984, 12, 24));
			m3.setCurrentCity("Pingshan");
			m3.setEducation(Education.MASTER);
			m3.setShortBio("integrate revolutionary communities");
			m3.setCurrentJobTitle("Programmer II");
			m3.setAvatar("https://robohash.org/suntutet.png?size=50x50&set=set1");
			Member m4 = new Member();
			m4.setUsername("cdonlon3");
			m4.setPassword("3clWpve");
			m4.setEmail("jdimanche3@wufoo.com");
			m4.setGender(Gender.MALE);
			m4.setCourseTaken("Python");
			m4.setBirthday(LocalDate.of(1985, 12, 12));
			m4.setCurrentCity("Kuchinarai");
			m4.setEducation(Education.DOCTORAL);
			m4.setShortBio("incentivize sexy functionalities");
			m4.setCurrentJobTitle("Chemical Engineer");
			m4.setAvatar("https://robohash.org/cumvelrepellendus.png?size=50x50&set=set1");
			Member m5 = new Member();
			m5.setUsername("mpickervance4");
			m5.setPassword("bmDXZ8ry");
			m5.setEmail("ulegen4@123-reg.co.uk");
			m5.setGender(Gender.FEMALE);
			m5.setBirthday(LocalDate.of(1990, 12, 16));
			m5.setCurrentCity("Funes");
			m5.setCourseTaken("MySQL");
			m5.setEducation(Education.DIPLOMA);
			m5.setShortBio("monetize B2C e-business");
			m5.setCurrentJobTitle("Office Assistant I");
			m5.setAvatar("https://robohash.org/exercitationemutaut.png?size=50x50&set=set1");
			Member m6 = new Member();
			m6.setUsername("pivanyukov5");
			m6.setPassword("NzkHJEXC");
			m6.setEmail("mschinetti5@guardian.co.uk");
			m6.setGender(Gender.MALE);
			m6.setCourseTaken("Neural Network");
			m6.setBirthday(LocalDate.of(1993, 10, 30));
			m6.setCurrentCity("Bilajari");
			m6.setEducation(Education.OTHERS);
			m6.setShortBio("deploy visionary action-items");
			m6.setCurrentJobTitle("Junior Executive");
			m6.setAvatar("https://robohash.org/officiiserrorrepellendus.png?size=50x50&set=set1");
			Member m7 = new Member();
			m7.setUsername("jgreenhaugh6");
			m7.setPassword("x2ExN8ht");
			m7.setEmail("wpriestley6@unc.edu");
			m7.setGender(Gender.MALE);
			m7.setCourseTaken("ASP.NET");
			m7.setBirthday(LocalDate.of(1992, 12, 19));
			m7.setCurrentCity("El Suyatal");
			m7.setEducation(Education.BACHELOR);
			m7.setShortBio("enhance killer relationships");
			m7.setCurrentJobTitle("Physical Therapy Assistant");
			m7.setAvatar("https://robohash.org/voluptatesaperiamfacere.png?size=50x50&set=set1");
			ccRepo.saveAndFlush(cc1);
			ccRepo.saveAndFlush(cc2);
			ccRepo.saveAndFlush(cc3);
			ccRepo.saveAndFlush(cc4);
			ccRepo.saveAndFlush(cc5);
			ccRepo.saveAndFlush(cc6);
			ccRepo.saveAndFlush(cc7);
			ccRepo.saveAndFlush(cc8);
			ccRepo.saveAndFlush(cc9);
			ccRepo.saveAndFlush(cc10);
			ccRepo.saveAndFlush(cc11);
			ccRepo.saveAndFlush(cc12);
			ccRepo.saveAndFlush(cc13);
			ccRepo.saveAndFlush(cc14);
			ccRepo.saveAndFlush(cc15);
			ccRepo.saveAndFlush(cc16);
			ccRepo.saveAndFlush(cc17);
			ccRepo.saveAndFlush(cc18);
			ccRepo.saveAndFlush(cc19);
			ccRepo.saveAndFlush(cc20);

			cc2.setSkill(s1);
			ccRepo.save(cc2);
			cc3.setSkill(s1);
			ccRepo.save(cc3);
			cc4.setSkill(s2);
			ccRepo.save(cc4);
			cc5.setSkill(s1);
			ccRepo.save(cc5);
			cc6.setSkill(s2);
			ccRepo.save(cc6);
			cc7.setSkill(s1);
			ccRepo.save(cc7);
			cc8.setSkill(s2);
			ccRepo.save(cc8);

			sRepo.save(s1);
			sRepo.save(s2);
			sRepo.save(s3);
			sRepo.save(s4);
			sRepo.save(s5);
			sRepo.save(s6);
			sRepo.save(s7);
			sRepo.save(s8);
			sRepo.save(s9);
			sRepo.save(s10);
			sRepo.save(s11);
			sRepo.save(s12);
			sRepo.save(s13);
			sRepo.save(s14);
			sRepo.save(s15);
			sRepo.save(s16);
			sRepo.save(s17);
			sRepo.save(s18);
			sRepo.save(s19);
			sRepo.save(s20);

			mRepo.createMember(m1);
			mRepo.createMember(m2);
			mRepo.createMember(m3);
			mRepo.createMember(m4);
			mRepo.createMember(m5);
			mRepo.createMember(m6);
			mRepo.createMember(m7);


			mRepo.save(m1);
			mRepo.save(m2);
			mRepo.save(m3);
			mRepo.save(m4);
			mRepo.save(m5);
			mRepo.save(m6);
			mRepo.save(m7);

			MyCourse mc1 = new MyCourse();
			mc1.setProgress(12);
			mc1.setSkill(s1.getSkillId());
			mc1.setMember(m1);
			mc1.setMyCourseTitle("Spring Framework 5: Beginner to Guru");
			MyCourse mc2 = new MyCourse();
			mc2.setProgress(80);
			mc2.setSkill(s2.getSkillId());
			mc2.setMember(m1);
			mc2.setMyCourseTitle("DevOps Beginners to Advanced");
			MyCourse mc3 = new MyCourse();
			mc3.setProgress(64);
			mc3.setSkill(s3.getSkillId());
			mc3.setMember(m2);
			mc3.setMyCourseTitle("Master Spring Boot 3 & Spring Framework 6 with Java");
			MyCourse mc4 = new MyCourse();
			mc4.setProgress(31);
			mc4.setSkill(s4.getSkillId());
			mc4.setMember(m2);
			mc4.setMyCourseTitle("Python for Data Science and Machine Learning Bootcamp");
			MyCourse mc5 = new MyCourse();
			mc5.setProgress(44);
			mc5.setSkill(s5.getSkillId());
			mc5.setMember(m3);
			mc5.setMyCourseTitle("Spring Boot JPA");
			MyCourse mc6 = new MyCourse();
			mc6.setProgress(26);
			mc6.setSkill(s6.getSkillId());
			mc6.setMember(m3);
			mc6.setMyCourseTitle("Spring&Hibernate for Beginner");
			MyCourse mc7 = new MyCourse();
			mc7.setProgress(20);
			mc7.setSkill(s7.getSkillId());
			mc7.setMember(m4);
			mc7.setMyCourseTitle("Full stack:React and Java Spring Boot");
			MyCourse mc8 = new MyCourse();
			mc8.setProgress(86);
			mc8.setSkill(s8.getSkillId());
			mc8.setMember(m4);
			mc8.setMyCourseTitle("Full Android Development Masterclass");
			MyCourse mc9 = new MyCourse();
			mc9.setProgress(99);
			mc9.setSkill(s9.getSkillId());
			mc9.setMember(m5);
			mc9.setMyCourseTitle("Web Scraping in Python");
			MyCourse mc10 = new MyCourse();
			mc10.setProgress(21);
			mc10.setSkill(s10.getSkillId());
			mc10.setMember(m5);
			mc10.setMyCourseTitle("C++ Programming For Beginners");
			MyCourse mc11 = new MyCourse();
			mc11.setProgress(100);
			mc11.setSkill(s3.getSkillId());
			mc11.setMember(m1);
			mc11.setMyCourseTitle("Flutter Programming For Beginners");
			MyCourse mc12 = new MyCourse();
			mc12.setProgress(99);
			mc12.setSkill(s4.getSkillId());
			mc12.setMember(m1);
			mc12.setMyCourseTitle("Ruby Programming For Beginners");
			mc1.setThumbnail("https://www.shutterstock.com/image-vector/smile-icon-logo-vector-template-600w-1491409253.jpg");
			mc2.setThumbnail("https://www.shutterstock.com/image-vector/smile-icon-logo-vector-template-600w-1491409253.jpg");
			mc3.setThumbnail("https://www.shutterstock.com/image-vector/smile-icon-logo-vector-template-600w-1491409253.jpg");
			mc4.setThumbnail("https://www.shutterstock.com/image-vector/smile-icon-logo-vector-template-600w-1491409253.jpg");
			mc5.setThumbnail("https://www.shutterstock.com/image-vector/smile-icon-logo-vector-template-600w-1491409253.jpg");
			mc6.setThumbnail("https://www.shutterstock.com/image-vector/smile-icon-logo-vector-template-600w-1491409253.jpg");
			mc7.setThumbnail("https://www.shutterstock.com/image-vector/smile-icon-logo-vector-template-600w-1491409253.jpg");
			mc8.setThumbnail("https://www.shutterstock.com/image-vector/smile-icon-logo-vector-template-600w-1491409253.jpg");
			mc9.setThumbnail("https://www.shutterstock.com/image-vector/smile-icon-logo-vector-template-600w-1491409253.jpg");
			mc10.setThumbnail("https://www.shutterstock.com/image-vector/smile-icon-logo-vector-template-600w-1491409253.jpg");
			mc11.setThumbnail("https://www.shutterstock.com/image-vector/smile-icon-logo-vector-template-600w-1491409253.jpg");
			mc12.setThumbnail("https://www.shutterstock.com/image-vector/smile-icon-logo-vector-template-600w-1491409253.jpg");
			mc1.setCourseUrl("https://www.youtube.com/watch?v=9yzMKaKcoC0");
			mc2.setCourseUrl("https://www.youtube.com/watch?v=9yzMKaKcoC0");
			mc3.setCourseUrl("https://www.youtube.com/watch?v=9yzMKaKcoC0");
			mc4.setCourseUrl("https://www.youtube.com/watch?v=9yzMKaKcoC0");
			mc5.setCourseUrl("https://www.youtube.com/watch?v=9yzMKaKcoC0");
			mc6.setCourseUrl("https://www.youtube.com/watch?v=9yzMKaKcoC0");
			mc7.setCourseUrl("https://www.youtube.com/watch?v=9yzMKaKcoC0");
			mc8.setCourseUrl("https://www.youtube.com/watch?v=9yzMKaKcoC0");
			mc9.setCourseUrl("https://www.youtube.com/watch?v=9yzMKaKcoC0");
			mc10.setCourseUrl("https://www.youtube.com/watch?v=9yzMKaKcoC0");
			mc11.setCourseUrl("https://www.youtube.com/watch?v=9yzMKaKcoC0");
			mc12.setCourseUrl("https://www.youtube.com/watch?v=9yzMKaKcoC0");


			MySkill ms1 = new MySkill();
			ms1.setSkill(s1);
			ms1.setCourseTaken("Panther");
			MySkill ms2 = new MySkill();
			ms2.setSkill(s2);
			ms2.setCourseTaken("Even Angels Eat Beans");
			MySkill ms3 = new MySkill();
			ms3.setSkill(s3);
			ms3.setCourseTaken("Best in Show");
			MySkill ms4 = new MySkill();
			ms4.setSkill(s4);
			ms4.setCourseTaken("I Am Trying to Break Your Heart");
			MySkill ms5 = new MySkill();
			ms5.setSkill(s5);
			ms5.setCourseTaken("Cabin in the Woods, The");
			MySkill ms6 = new MySkill();
			ms6.setSkill(s6);
			ms6.setCourseTaken("American Astronaut, The");
			MySkill ms7 = new MySkill();
			ms7.setSkill(s7);
			ms7.setCourseTaken("To the Shores of Tripoli");
			MySkill ms8 = new MySkill();
			ms8.setSkill(s8);
			ms8.setCourseTaken("Capturing the Friedman");
			MySkill ms9 = new MySkill();
			ms9.setSkill(s9);
			ms9.setCourseTaken("Kill Me Again");
			MySkill ms10 = new MySkill();
			ms10.setSkill(s10);
			ms10.setCourseTaken("Lunch Break");

			Job j1 = new Job();
			j1.setJobTitle("Teacher");
			Job j2 = new Job();
			j2.setJobTitle("VP Quality Control");
			Job j3 = new Job();
			j3.setJobTitle("Teacher");
			Job j4 = new Job();
			j4.setJobTitle("Electrical Engineer");
			Job j5 = new Job();
			j5.setJobTitle("Assistant Professor");
			Job j6 = new Job();
			j6.setJobTitle("Staff Scientist");
			Job j7 = new Job();
			j7.setJobTitle("Help Desk Operator");
			Job j8 = new Job();
			j8.setJobTitle("Financial Advisor");
			Job j9 = new Job();
			j9.setJobTitle("Cost Accountant");
			Job j10 = new Job();
			j10.setJobTitle("Help Desk Technician");
			Job j11 = new Job();
			j11.setJobTitle("Financial Analyst");
			Job j12 = new Job();
			j12.setJobTitle("Food Chemist");
			Job j13 = new Job();
			j13.setJobTitle("Internal Auditor");
			Job j14 = new Job();
			j14.setJobTitle("Analog Circuit Design manager");
			Job j15 = new Job();
			j15.setJobTitle("Occupational Therapist");
			Job j16 = new Job();
			j16.setJobTitle("Safety Technician IV");
			Job j17 = new Job();
			j17.setJobTitle("Business Systems Development Analyst");
			Job j18 = new Job();
			j18.setJobTitle("Paralegal");
			Job j19 = new Job();
			j19.setJobTitle("Software Consultant");
			Job j20 = new Job();
			j20.setJobTitle("Technical Writer");

			JobSkill js1 = new JobSkill();
			js1.setJob(j1);
			js1.setSkill(s1);
			js1.setLastUpdatedDate(LocalDate.of(2022, 4, 10));
			JobSkill js2 = new JobSkill();
			js2.setJob(j2);
			js2.setSkill(s2);
			js2.setLastUpdatedDate(LocalDate.of(2022, 12, 11));
			JobSkill js3 = new JobSkill();
			js3.setJob(j3);
			js3.setSkill(s3);
			js3.setLastUpdatedDate(LocalDate.of(2022, 6, 01));
			JobSkill js4 = new JobSkill();
			js4.setJob(j4);
			js4.setSkill(s4);
			js4.setLastUpdatedDate(LocalDate.of(2022, 3, 07));
			JobSkill js5 = new JobSkill();
			js5.setJob(j5);
			js5.setSkill(s5);
			js5.setLastUpdatedDate(LocalDate.of(2022, 9, 24));
			JobSkill js6 = new JobSkill();
			js6.setJob(j6);
			js6.setSkill(s6);
			js6.setLastUpdatedDate(LocalDate.of(2022, 10, 06));
			JobSkill js7 = new JobSkill();
			js7.setJob(j7);
			js7.setSkill(s7);
			js7.setLastUpdatedDate(LocalDate.of(2022, 8, 17));
			JobSkill js8 = new JobSkill();
			js8.setJob(j8);
			js8.setSkill(s8);
			js8.setLastUpdatedDate(LocalDate.of(2022, 8, 10));
			JobSkill js9 = new JobSkill();
			js9.setJob(j9);
			js9.setSkill(s9);
			js9.setLastUpdatedDate(LocalDate.of(2022, 10, 24));
			JobSkill js10 = new JobSkill();
			js10.setJob(j10);
			js10.setSkill(s10);
			js10.setLastUpdatedDate(LocalDate.of(2022, 11, 25));
			JobSkill js11 = new JobSkill();
			js11.setJob(j11);
			js11.setSkill(s11);
			js11.setLastUpdatedDate(LocalDate.of(2022, 7, 3));
			JobSkill js12 = new JobSkill();
			js12.setJob(j12);
			js12.setSkill(s12);
			js12.setLastUpdatedDate(LocalDate.of(2022, 11, 27));
			JobSkill js13 = new JobSkill();
			js13.setJob(j13);
			js13.setSkill(s13);
			js13.setLastUpdatedDate(LocalDate.of(2022, 6, 5));
			JobSkill js14 = new JobSkill();
			js14.setJob(j14);
			js14.setSkill(s14);
			js14.setLastUpdatedDate(LocalDate.of(2022, 12, 8));
			JobSkill js15 = new JobSkill();
			js15.setJob(j15);
			js15.setSkill(s15);
			js15.setLastUpdatedDate(LocalDate.of(2022, 6, 27));
			JobSkill js16 = new JobSkill();
			js16.setJob(j16);
			js16.setSkill(s16);
			js16.setLastUpdatedDate(LocalDate.of(2022, 4, 20));
			JobSkill js17 = new JobSkill();
			js17.setJob(j17);
			js17.setSkill(s17);
			js17.setLastUpdatedDate(LocalDate.of(2022, 9, 5));
			JobSkill js18 = new JobSkill();
			js18.setJob(j18);
			js18.setSkill(s18);
			js18.setLastUpdatedDate(LocalDate.of(2022, 3, 26));
			JobSkill js19 = new JobSkill();
			js19.setJob(j19);
			js19.setSkill(s19);
			js19.setLastUpdatedDate(LocalDate.of(2022, 8, 16));
			JobSkill js20 = new JobSkill();
			js20.setJob(j20);
			js20.setSkill(s20);
			js20.setLastUpdatedDate(LocalDate.of(2022, 2, 23));


			ScheduleEvent se1 = new ScheduleEvent();
			se1.setStartDate(LocalDateTime.of(2022, 5, 1, 0, 0));
			se1.setEndDate(LocalDateTime.of(2022, 12, 2, 0, 0));
			se1.setMyCourse(mc1);
			ScheduleEvent se2 = new ScheduleEvent();
			se2.setStartDate(LocalDateTime.of(2022, 10, 6, 0, 0));
			se2.setEndDate(LocalDateTime.of(2023, 4, 25, 0, 0));
			se2.setMyCourse(mc2);
			ScheduleEvent se3 = new ScheduleEvent();
			se3.setStartDate(LocalDateTime.of(2022, 12, 21, 0, 0));
			se3.setEndDate(LocalDateTime.of(2023, 1, 16, 0, 0));
			se3.setMyCourse(mc3);
			ScheduleEvent se4 = new ScheduleEvent();
			se4.setStartDate(LocalDateTime.of(2022, 8, 22, 0, 0));
			se4.setEndDate(LocalDateTime.of(2022, 9, 14, 0, 0));
			se4.setMyCourse(mc4);
			ScheduleEvent se5 = new ScheduleEvent();
			se5.setStartDate(LocalDateTime.of(2023, 1, 19, 0, 0));
			se5.setEndDate(LocalDateTime.of(2023, 4, 25, 0, 0));
			se5.setMyCourse(mc5);
			ScheduleEvent se6 = new ScheduleEvent();
			se6.setStartDate(LocalDateTime.of(2022, 11, 30, 0, 0));
			se6.setEndDate(LocalDateTime.of(2023, 3, 12, 0, 0));
			se6.setMyCourse(mc6);
			ScheduleEvent se7 = new ScheduleEvent();
			se7.setStartDate(LocalDateTime.of(2022, 6, 15, 0, 0));
			se7.setEndDate(LocalDateTime.of(2023, 3, 12, 0, 0));
			se7.setMyCourse(mc7);
			ScheduleEvent se8 = new ScheduleEvent();
			se8.setStartDate(LocalDateTime.of(2022, 4, 8, 0, 0));
			se8.setEndDate(LocalDateTime.of(2022, 11, 17, 0, 0));
			se8.setMyCourse(mc8);
			ScheduleEvent se9 = new ScheduleEvent();
			se9.setStartDate(LocalDateTime.of(2022, 10, 23, 0, 0));
			se9.setEndDate(LocalDateTime.of(2022, 11, 19, 0, 0));
			se9.setMyCourse(mc9);
			ScheduleEvent se10 = new ScheduleEvent();
			se10.setStartDate(LocalDateTime.of(2023, 1, 12, 0, 0));
			se10.setEndDate(LocalDateTime.of(2023, 4, 20, 0, 0));
			se10.setMyCourse(mc10);


			mc1.setScheduleEvent(se1);
			mc2.setScheduleEvent(se2);
			mc3.setScheduleEvent(se3);
			mc4.setScheduleEvent(se4);
			mc5.setScheduleEvent(se5);
			mc6.setScheduleEvent(se6);
			mc7.setScheduleEvent(se7);
			mc8.setScheduleEvent(se8);
			mc9.setScheduleEvent(se9);
			mc10.setScheduleEvent(se10);


			mRepo.save(m1);
			mRepo.save(m2);
			mRepo.save(m3);
			mRepo.save(m4);
			mRepo.save(m5);
			mRepo.save(m6);
			mRepo.save(m7);


			seRepo.save(se1);
			seRepo.save(se2);
			seRepo.save(se3);
			seRepo.save(se4);
			seRepo.save(se5);
			seRepo.save(se6);
			seRepo.save(se7);
			seRepo.save(se8);
			seRepo.save(se9);
			seRepo.save(se10);

			jsRepo.save(js1);
			jsRepo.save(js2);
			jsRepo.save(js3);
			jsRepo.save(js4);
			jsRepo.save(js5);
			jsRepo.save(js6);
			jsRepo.save(js7);
			jsRepo.save(js8);
			jsRepo.save(js9);
			jsRepo.save(js10);
			jsRepo.save(js11);
			jsRepo.save(js12);
			jsRepo.save(js13);
			jsRepo.save(js14);
			jsRepo.save(js15);
			jsRepo.save(js16);
			jsRepo.save(js17);
			jsRepo.save(js18);
			jsRepo.save(js19);
			jsRepo.save(js20);


			jRepo.save(j1);
			jRepo.save(j2);
			jRepo.save(j3);
			jRepo.save(j4);
			jRepo.save(j5);
			jRepo.save(j6);
			jRepo.save(j7);
			jRepo.save(j8);
			jRepo.save(j9);
			jRepo.save(j10);
			jRepo.save(j11);
			jRepo.save(j12);
			jRepo.save(j13);
			jRepo.save(j14);
			jRepo.save(j15);
			jRepo.save(j16);
			jRepo.save(j17);
			jRepo.save(j18);
			jRepo.save(j19);
			jRepo.save(j20);

			m1.setDreamJob(j1);
			m2.setDreamJob(j2);
			m3.setDreamJob(j3);
			m4.setDreamJob(j4);
			m5.setDreamJob(j5);
			m6.setDreamJob(j6);
			m7.setDreamJob(j7);


			msRepo.save(ms1);
			msRepo.save(ms2);
			msRepo.save(ms3);
			msRepo.save(ms4);
			msRepo.save(ms5);
			msRepo.save(ms6);
			msRepo.save(ms7);
			msRepo.save(ms8);
			msRepo.save(ms9);
			msRepo.save(ms10);

			ms1.setMember(m1);
			ms2.setMember(m2);
			ms3.setMember(m3);
			ms4.setMember(m4);
			ms5.setMember(m5);
			ms6.setMember(m6);
			ms7.setMember(m7);
			ms8.setMember(m1);
			ms9.setMember(m2);
			ms10.setMember(m3);

			se1.setMember(m1);
			se2.setMember(m2);
			se3.setMember(m3);
			se4.setMember(m4);
			se5.setMember(m5);
			se6.setMember(m6);
			se7.setMember(m7);
			se8.setMember(m1);
			se9.setMember(m2);
			se10.setMember(m3);

			seRepo.save(se1);
			seRepo.save(se2);
			seRepo.save(se3);
			seRepo.save(se4);
			seRepo.save(se5);
			seRepo.save(se6);
			seRepo.save(se7);
			seRepo.save(se8);
			seRepo.save(se9);
			seRepo.save(se10);

			mRepo.save(m1);
			mRepo.save(m2);
			mRepo.save(m3);
			mRepo.save(m4);
			mRepo.save(m5);
			mRepo.save(m6);
			mRepo.save(m7);


			msRepo.save(ms1);
			msRepo.save(ms2);
			msRepo.save(ms3);
			msRepo.save(ms4);
			msRepo.save(ms5);
			msRepo.save(ms6);
			msRepo.save(ms7);
			msRepo.save(ms8);
			msRepo.save(ms9);
			msRepo.save(ms10);

			mcRepo.save(mc1);
			mcRepo.save(mc2);
			mcRepo.save(mc3);
			mcRepo.save(mc4);
			mcRepo.save(mc5);
			mcRepo.save(mc6);
			mcRepo.save(mc7);
			mcRepo.save(mc8);
			mcRepo.save(mc9);
			mcRepo.save(mc10);
			mcRepo.save(mc11);
			mcRepo.save(mc12);


			ccRepo.saveAndFlush(cc1);
			ccRepo.saveAndFlush(cc2);
			ccRepo.saveAndFlush(cc3);
			ccRepo.saveAndFlush(cc4);
			ccRepo.saveAndFlush(cc5);
			ccRepo.saveAndFlush(cc6);
			ccRepo.saveAndFlush(cc7);
			ccRepo.saveAndFlush(cc8);
			ccRepo.saveAndFlush(cc9);
			ccRepo.saveAndFlush(cc10);
			ccRepo.saveAndFlush(cc11);
			ccRepo.saveAndFlush(cc12);
			ccRepo.saveAndFlush(cc13);
			ccRepo.saveAndFlush(cc14);
			ccRepo.saveAndFlush(cc15);
			ccRepo.saveAndFlush(cc16);
			ccRepo.saveAndFlush(cc17);
			ccRepo.saveAndFlush(cc18);
			ccRepo.saveAndFlush(cc19);
			ccRepo.saveAndFlush(cc20);

			sRepo.save(s1);
			sRepo.save(s2);
			sRepo.save(s3);
			sRepo.save(s4);
			sRepo.save(s5);
			sRepo.save(s6);
			sRepo.save(s7);
			sRepo.save(s8);
			sRepo.save(s9);
			sRepo.save(s10);
			sRepo.save(s11);
			sRepo.save(s12);
			sRepo.save(s13);
			sRepo.save(s14);
			sRepo.save(s15);
			sRepo.save(s16);
			sRepo.save(s17);
			sRepo.save(s18);
			sRepo.save(s19);
			sRepo.save(s20);

			mcRepo.saveAndFlush(mc1);
			mcRepo.saveAndFlush(mc2);
			mcRepo.saveAndFlush(mc3);
			mcRepo.saveAndFlush(mc4);
			mcRepo.saveAndFlush(mc5);
			mcRepo.saveAndFlush(mc6);
			mcRepo.saveAndFlush(mc7);
			mcRepo.saveAndFlush(mc8);
			mcRepo.saveAndFlush(mc9);
			mcRepo.saveAndFlush(mc10);

		};


	}}





